### ISSUE TITLE
Increase Horse Carry Weight

### ISSUE THREAD

**Issue by AsuraAce** [Cataclysm-TISH-team/Cataclysm-TISH#22]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/13394741/229582588-f2a26eb0-fa2f-4bc6-b7d3-fc3bfd9e08e5.png)

The current implementation does not allow a 185cm tall man wearing a ballistic vest and a rifle to mount a horse. This may be realistic for a specific type of horse breed, but it doesn´t factor in game limitations and it causes a lot of frustration.

### Solution you would like.

If the current implementation is based on the weight of the horse (carry capacity = 20% of the horses weight), than i would like to see the weight of a horse to be increased from 550kg (currently) to something like 800kg.

### Describe alternatives you have considered.

- add different breeds of horses
- add stamina system for horses

**Comment by Night-Pryanik** [comment]
I feel it's better to increase the percentage (to 30-35%) rather than increase horse's weight.

**Comment by AsuraAce** [comment]
ofc, that would work as well.

**Comment by GenericDwarf** [comment]
> I feel it's better to increase the percentage (to 30-35%) rather than increase horse's weight.

Why not both? 
The 20% carry limit comes from a study measuring at which point horses get affected by their carried weight, and while 20% of their body weight is where the weight was affecting the test horses, it wasn't until 35% that they started to show visible discomfort.
Also, a quick google search points out the average work horse weighs on average around 1400-2000lbs (600-900kg), so "bulking" the horses up is also reasonable.

**Comment by Night-Pryanik** [comment]
Well, while googling I found out that heavyweight work horse's weight start from 800 kg, but I'm not sure horses in Cata is this particular work breed.
