### ISSUE TITLE
Add - Separate Item Spawn Rate Category for Martial Art Books

### ISSUE THREAD

**Issue by AsuraAce** [Cataclysm-TISH-team/Cataclysm-TISH#26]
### Is your feature request related to a problem? Please describe.

would like to make use of the newly added category based item spawn rates. i want to decrease spawn rates for books (all categories), but this would decrease the small chance of getting a martial arts book as well. 

### Solution you would like.

a separate category for martial art books in the category based item spawn rate menu.

**Comment by Night-Pryanik** [comment]
Martial arts books are located in `manuals` category.

**Comment by AsuraAce** [comment]
sorry, i just mentioned books because i thought they where in this category. 

i will decrease all categories but i want to keep a decent chance of getting a martial arts book. i may even increase the chance for martial art books if the feature is added (will definitely play around with increased chance based on the character i play)

**Comment by Night-Pryanik** [comment]
Can be closed then?

**Comment by AsuraAce** [comment]
No. Manuals would include "recipe books" / books that increase your skill level and have recipes if I'm not mistaken. Would like to change the item spawn rate for martial art books on their own.
