### ISSUE TITLE
Merge "drag heavier vehicles" change that was not accepted in DDA

### ISSUE THREAD

**Issue by Raikiri** [Cataclysm-TISH-team/Cataclysm-TISH#30]
### Is your feature request related to a problem? Please describe.

One of the most hyped changes that was closed in DDA was this one https://github.com/CleverRaven/Cataclysm-DDA/pull/63737
Can we merge it here?

### Solution you would like.

I'd like that pull request to be merged into TISH instead

**Comment by Night-Pryanik** [comment]
It's already here - #27.
