### ISSUE TITLE
Red Phosphorus weirdly insists on using matchbooks or matchboxes, instead of matches themselves

### ISSUE THREAD

**Issue by lbnesquik** [Cataclysm-TISH-team/Cataclysm-TISH#77]
### Is your feature request related to a problem? Please describe.

I've just found the recipe for red phosphorus. It involves grinding matches into the reactive paste they are coated in. However, it only wants the boxes, instead of the matches themselves. You can physically have a big pile of matches, and it will insist on you using those two options, instead of the more obvious one.

### Solution you would like.

I think a correction to the recipe might solve the issue easily. 'Just' make it so you can use matches directly, and perhaps leave the box alone too. 

### Additional context

![image](https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/assets/24830358/4d21274c-eff5-4c29-918b-a8fdc771dfe2)

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: f319ad5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

**Comment by Night-Pryanik** [comment]
Comment from @Vaskritaya in https://github.com/CleverRaven/Cataclysm-DDA/pull/65777:

> From what I understand, red phosphorous doesn't come from matchheads, it comes from the pad on the boxes you strike the match against. see https://www.youtube.com/watch?v=5ZrfNAHDjWU

So it's working as intended.
